### PR TITLE
Log stack trace to console for exceptions.

### PR DESCRIPTION
**Pull request by ryneeverett**
I also fixed some inconsistent indentation in these sections.

### CODE REVIEW

**Comment by ryneeverett** [comment]
The issue is that you're catching the exceptions and logging the exception message without re-throwing the exception, effectively suppressing the stack trace which makes debugging difficult.

Yes, this approach does introduce duplication of the exception message which is also included in the stack trace. There are a couple alternatives:

1. Pass the whole stack trace into chalk, i.e. `"Reason: ${err.stack}"`, which would make the entire traceback red.
2. Only log the stack trace if a `-d/--debug` flag is passed. This is the approach HackMyResume takes (which does duplicate the exception message) but I don't recommend it. Anyone using a cli tool can handle a stack trace.

**Comment by karlitos** [comment]
Oh I see, didn't thought about the stack trace. I wouldn't say  we should always log the stacktrace  because "it's CLI  tool". The first reason is readability - even a CLI tool shouldn't always overwhelm the user with tons of output. Second, I hope I would be able to start to work on a GUI using electron and some library generating forms from JSON-Schema. For that, extending the logging wrappers would be necessary and my first reason would apply even more.

Nevertheless, the `-d/--debug`  is a great Idea and very meaningful extension. I try to find some time soon to implement it.

Thus, I would prefer to omit the doubled `console.error` calls in the code.

**Comment by ryneeverett** [comment]
I guess I wouldn't mind the `-d/--debug` flag so much if a message was added to `logError` like `"please run with -d/--debug for full stack trace"` so that one doesn't have to puzzle over a brief and unhelpful error message.

**Comment by karlitos** [comment]
I found some time to look at the `debug` flag. I actually don't want to set another parameter to each command and I think it might be useful to respect the global __debug level__. I didn't find a way to do it directly and it seems to me that there might be a bug in caporal, see [my bugreport](https://github.com/mattallty/Caporal.js/issues/172#)

**Comment by karlitos** [comment]
I updated KissMyResume to use the Caporal V2 and added the support for the global verbose mode, see f9f3452

**Pull request closed without merging**
